_target_: src.reskan.SlimResKANLightning
in_ch: 3
feat_ch: 64
num_steps: 8
kan_K: 32
kan_R: 8
share_block: True
lr: 2e-4
wd: 1e-8
lambda_charb: 1.0
lambda_l1: 0.5
lambda_tv: 0.0
lambda_sobolev: 5e-4
lambda_group: 1e-4
